version: '3.8'
services:
  reservation-service:
    build: .
    ports:
      - "8082:8082"
    networks:
      - my-network
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/

networks:
  my-network:
    driver: bridge
